// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMk7xudAsBJWO-XtQNK1-XfW042BJtXdk',
    appId: '1:125500308622:web:6561ab41fbde18f481dddf',
    messagingSenderId: '125500308622',
    projectId: 'evently-app-6023b',
    authDomain: 'evently-app-6023b.firebaseapp.com',
    storageBucket: 'evently-app-6023b.firebasestorage.app',
    measurementId: 'G-K3CS6SPLJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKnbQDWL4mlAaw6GGhGlac9ismat72O5o',
    appId: '1:125500308622:android:b631e3a3ee1edb1581dddf',
    messagingSenderId: '125500308622',
    projectId: 'evently-app-6023b',
    storageBucket: 'evently-app-6023b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUbg9pIwrVlV0A99OiMamhYvwM91bRDe8',
    appId: '1:125500308622:ios:5601f098921b0fd081dddf',
    messagingSenderId: '125500308622',
    projectId: 'evently-app-6023b',
    storageBucket: 'evently-app-6023b.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );
}
